### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [lkorth/auto-fi#1]
Would you mind attaching the `.apk` to the corresponding `releases/`, so folks without Playstore can grab it? Thanks in advance!

**Comment by lkorth** [comment]
The easiest route would be to include Auto Fi on F-Droid, however it currently violates a few of the items in the [inclusion policy](https://f-droid.org/wiki/page/Inclusion_Policy) and thus cannot be published there. I've included an APK in the latest release.

**Comment by IzzySoft** [comment]
And [thus it begins](https://apt.izzysoft.de/fdroid/index/apk/com.lukekorth.auto_fi) :smile_cat: Yeah, whether Firebase is a good choice in connection with OpenSource and privacy might be doubtful. Quoting:

> From firebase site: "[Firebase] helps you quickly [...] earn more money.", "At the heart of Firebase is Firebase Analytics", "Earn money by displaying engaging ads"... 

([mousetodon](https://github.com/cerisara/mousetodon))

I'm not an Android dev myself, so it's hard to argue what might be "better fitting". I've run an analysis and did some research on modules lately, though (see: [What’s it all about those modules apps contain?](https://android.izzysoft.de/articles/named/app-modules-1)), and from that *it seems* Crashlytics is the cleaner alternative, privacy-wise.

PS: Whenever you tag a new release and add the `.apk` to it, my repo-updater will automatically pick it. So basically it can now be installed (and kept up-to-date) using the F-Droid client, though not being on the "official repo".

**Comment by IzzySoft** [comment]
@lkorth could you also add the latest version's APK? Still missing 😉

**Comment by lkorth** [comment]
I've stopped hosting the VPN server for this app and haven't been doing any development on it since many things it requires from Android are not longer available beyond API 26.

**Comment by IzzySoft** [comment]
Thanks for your reply! In that case, may I recommend you "archive" this repo (can be done from the repo's settings, and can be undone if needed) to show it's no longer under development?
